spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #데베 상태 유지
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100

  logging:
    level:
      org.hibernate.SQL:debug