spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab
    password: 1234
    username: root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
