spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: 1234
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false #스프링이 아닌 우리 코드로 실행하겠다는 의미